accordion task
js-tasks-ru/htmlcss-20220519_gnessssa pull request #5
Opened 2022-06-02 15:43 UTC by gnessssa

2022-06-02 15:44 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-06-05 10:42 UTC, GSemikozov requested changes

2022-06-05 10:42 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +.accordion *{
ой, универсальный селектор, особенно для задания шрифта, как мы видели, это не оч хорошая практика) так что - шрифт задаем просто на .accordion

2022-06-06 14:07 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-06-07 17:49 UTC, GSemikozov approved these changes

2022-06-07 17:49 UTC, merged